# Numpy

It's fullform is numerical python and takes less memory size.

It is faster then normal array list

In [1]:
import numpy as np

In [6]:
a = [i for i in range(0,10)]
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
a = [1,2,3,4,5]
np.array(a,dtype=str)
# str/int/float passing these value in dtype will comvert to particular data type

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [9]:
# make replica
a*3

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [10]:
np.ones(3)

array([1., 1., 1.])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [15]:
np.full((3,2),2)

array([[2, 2],
       [2, 2],
       [2, 2]])

# NumPy 2D array

Problem Statement:

GIven a 2D list, create a numpy 2D array using it.

Note: Given 2D list is [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Print the Numpy array.

In [16]:
import numpy as np 
li = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
arr = np.array(li)

print(arr, end=' ')

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

# NumPy 0s and 1s

Problem Statement:

Create an integer array of size 10, where all the values should be 0 but the fifth value should be 1.

Print the elements of array.

In [17]:
import numpy as np

li = np.zeros(10, dtype=int)
li[4] = 1
for i in li:
    print(i, end=' ')

0 0 0 0 1 0 0 0 0 0 

In [19]:
# arange method
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
a = np.arange(2,10,2)
a

array([2, 4, 6, 8])

In [25]:
b= np.linspace(2,10)
b
#it will print by default 50 values between 2-10 

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [28]:
np.identity(3)
# it will show square matrix always

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [29]:
np.random.rand(3)

array([0.70254223, 0.3342131 , 0.3469822 ])

In [30]:
np.random.rand(10)*10

array([1.15767522, 2.83019117, 2.58945697, 4.20284958, 5.33322918,
       4.31970195, 0.94223429, 0.85763   , 6.01395198, 3.39039595])

In [31]:
a.shape

(4,)

In [39]:
np.random.rand(10,4)

array([[0.50087319, 0.72821512, 0.04838066, 0.39459148],
       [0.34475029, 0.48595495, 0.41780023, 0.21346311],
       [0.54874744, 0.89935009, 0.04602803, 0.64044417],
       [0.84739956, 0.09367472, 0.95564159, 0.66997527],
       [0.45677571, 0.18411785, 0.47232296, 0.02205715],
       [0.52787474, 0.3086597 , 0.09169593, 0.04320009],
       [0.25498202, 0.70477002, 0.86704163, 0.0269735 ],
       [0.70955902, 0.39824177, 0.71582644, 0.40165052],
       [0.65844314, 0.87362571, 0.5144618 , 0.46623846],
       [0.08239163, 0.94985434, 0.37904653, 0.15579757]])

In [40]:
np.random.randint(10,size=(4,4))

array([[3, 5, 3, 5],
       [3, 5, 1, 2],
       [0, 7, 8, 8],
       [6, 0, 4, 6]])

# NumPy Inclusive

Problem Statement:

Create an array with values ranging consecutively from 9 to 49 (both inclusive).
Print the Numpy array.

In [41]:
import numpy as np

arr = np.arange(9,50)

print(*arr)

9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49


# Identity Matrix

Problem Statement:
Create an integer identity matrix of size (5, 6).
Print the Numpy array.

In [42]:
import numpy as np
arr = np.eye(5,6,dtype=int)

print(arr,end='')

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]]

# Cut the Rope

Problem Statement:
You are given a rope of length 5m. Cut the rope into 9 parts such that each part is of equal length.
Note:Array elements are the points where cut is to be made and round upto 2 decimal place.
Print the array element.

In [43]:
import numpy as np

start = 0
end = 5
no_of_points = 10
for i in np.linspace(start, end, no_of_points)[1:9]:
    print(format(i, '.2f'))
    

0.56
1.11
1.67
2.22
2.78
3.33
3.89
4.44


In [45]:
print(a.data)
print(a.shape)
print(a.dtype)
print(a.strides)

(4,)
int32
(4,)


# Mathematical Operations

In [49]:
li = [1,2,3,4,5]
a = np.random.randint(1,20,5)
b = np.random.randint(1,20,5)

In [50]:
li = [i+1 for i in li]
li

[2, 3, 4, 5, 6]

In [51]:
a = a+1
a

array([ 4, 15, 10,  5,  6])

In [53]:
c = a+b
c

array([14, 22, 12,  6, 10])

In [54]:
d = a-b
d

array([-6,  8,  8,  4,  2])

In [55]:
e = a*b
e

array([ 40, 105,  20,   5,  24])

In [56]:
f = a/b
f

array([0.4       , 2.14285714, 5.        , 5.        , 1.5       ])

In [57]:
g = a//b
g

array([0, 2, 5, 5, 1], dtype=int32)

In [59]:
h = a**b
h

array([  1048576, 170859375,       100,         5,      1296], dtype=int32)

In [60]:
print(a.sum())
print(a.min())
print(a.max())
print(a.argmin())
print(a.argmax())

40
4
15
0
1


In [61]:
print(a)
print(b)
a>b

[ 4 15 10  5  6]
[10  7  2  1  4]


array([False,  True,  True,  True,  True])

In [65]:
print(a<b)
print(a==b)
print(np.logical_or(a,b))
print(np.logical_and(a,b))
a[2] =0
print(np.logical_not(a))

[False False  True False False]
[False False False False False]
[ True  True  True  True  True]
[False False False False False]
[False False  True False False]


In [67]:
# to get only true condition value
b = a[a>5]
b

array([15,  6])

In [68]:
b = a[(a>5) & (a<10)]
b

array([6])

In [72]:
a[:3] = 10

In [73]:
a

array([10, 10, 10,  5,  6])

In [74]:
a[a<6] = 32
a

array([10, 10, 10, 32,  6])

In [77]:
print(a[a == 10])

[10 10 10]


In [78]:
b = np.where(a ==10)
b

(array([0, 1, 2], dtype=int64),)

In [79]:
a[b]

array([10, 10, 10])

# Replace Max

Problem Statemnt:

Given an integer array of size 10 and replace the first occurrence of maximum value by 0?

Note: Generate the following array

array([11, 2, 13, 4, 15, 6, 27, 8, 19])

In [82]:
import numpy as np
a = np.array([11, 2, 13, 4, 15, 6, 27, 8, 19])

g=max(a)
max_index = np.where(a == g)
a[max_index] = 0
print(*a)

11 2 13 4 15 6 0 8 19


# Negate Elements

Problem Statemnt:

Given a 1D array, negate all elements which are between 3 and 8 (both inclusive)?

Note: Generate the following array

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [85]:
nparray=np.arange(1,11,1)
index=np.where((nparray >=3) & (nparray <=8))
for i in index:
    nparray[i]=np.negative(nparray[i])
for i in nparray:
    print(i)

1
2
-3
-4
-5
-6
-7
-8
9
10


# Sort by column

Problem Statemnt:

Sort a given 2D array of shape (4, 5) by 2nd column (i.e. column at index 1) in ascending order.
That means, we should re-arrange complete row based on 2nd columns' values

In [86]:
arr = np.array([[21, 20 ,19, 18, 17],
  [16, 15 ,14, 13 ,12],
  [11 ,10 , 9 , 8 , 7],
  [ 6  ,5,  4  ,3,  2]])

sorted_arr = arr[:,1].argsort()
print(arr[sorted_arr])

[[ 6  5  4  3  2]
 [11 10  9  8  7]
 [16 15 14 13 12]
 [21 20 19 18 17]]


# Broadcasting

In [91]:
a= np.random.randint(1,10,(2,3))
b= np.random.randint(1,10,(3,2))
a

array([[6, 1, 8],
       [8, 5, 1]])

In [92]:
# transpose the matrix to make compatible
a = a.transpose()
a

array([[6, 8],
       [1, 5],
       [8, 1]])

In [95]:
c = a-b
c

array([[-2,  3],
       [-3,  4],
       [ 2, -3]])

# resize & reshape also used for the same 

In [98]:
a = a.reshape(3,2)
a

array([[6, 8],
       [1, 5],
       [8, 1]])